/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.contacteditor;

import java.awt.Image;
import java.io.File;
import java.io.IOException;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.LineUnavailableException;
import javax.swing.ImageIcon;

/**
 *
 * @author Ahmet Engin
 */
public class ContactEditorUI extends javax.swing.JFrame{
  
   
    private AudioInputStream playButtonSound;
    private AudioInputStream OptionButtonSound;
    private AudioInputStream QuitButtonSound;
    private AudioInputStream BackgrounSound;
    private ImageIcon MenuIcon;
    private Clip clip1;//Options daki ses
    private Clip clip2;// Play tuşundaki ses
    private Clip clip3 ;// Arkaplan müziği
    private boolean isOpen = true;
    private float volumeOfMusic =6f ;
    ;

    public void setIsOpen(boolean isOpen) {
        this.isOpen = isOpen;
    }

  

   
    public void setVolumeOfMusic(float volumeOfMusic) {
        this.volumeOfMusic = volumeOfMusic;
    }
  
    
    public void ChangeVolumeMusic(float volume) throws LineUnavailableException, IOException{
       
     FloatControl gainControl = (FloatControl) clip3.getControl(FloatControl.Type.MASTER_GAIN);  
    
    gainControl.setValue(volume);
    
     
    }
    
    
    private void setBackgroundMuisc(){
       
        try{
            BackgrounSound = AudioSystem.getAudioInputStream(new File("tree.wav"));
            clip3 = AudioSystem.getClip();
            clip3.open(BackgrounSound);
            clip3.start();
            
            clip3.loop(Clip.LOOP_CONTINUOUSLY);
            
        }catch(Exception e){
            System.out.println("Hata varrrr");
        }
       
    }
    

    /**
     * Creates new form ContactEditorUI
     */
    public ContactEditorUI(){
        this.setTitle("Melody Tiles");
        try {
             clip2 = AudioSystem.getClip();
             clip1 = AudioSystem.getClip();
        } catch (Exception e) {
            System.out.println("Ben malım");
        }
      
       Image reScaledIMage = new ImageIcon("tree.jpg").getImage().getScaledInstance(250, 250, Image.SCALE_DEFAULT);
        MenuIcon = new ImageIcon(reScaledIMage);
        initComponents();
        setBackgroundMuisc();
        setVisible(true);
        

    }
   public void init() throws LineUnavailableException, IOException{
    
      
       initComponents();
       setBackgroundMuisc();
       ChangeVolumeMusic(volumeOfMusic);
      
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(665, 479));
        setResizable(false);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Play");
        jButton1.setAlignmentY(0.0F);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Option");
        jButton2.setToolTipText("Lütfen sürekli fareyi bu düğmenin üzeriden geçirmeyin !!!!!!");
        jButton2.setAlignmentY(0.0F);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Quit");
        jButton3.setAlignmentY(0.0F);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(MenuIcon
        );
        jLabel2.setToolTipText("Eğer bilgisayarın varsa ve 25 yaşındaysan kesinlikle bu oyunu oynamalısın");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton3))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
       
         if(isOpen){
                
            // TODO add your handling code here:
           try{
             
          playButtonSound =  AudioSystem.getAudioInputStream(new File("316899__jaz-the-man-2__do-stretched.wav").getAbsoluteFile());
         
            clip2 = AudioSystem.getClip();
            clip2.open(playButtonSound);
            clip2.start();

            
               
           }catch(Exception ex){
               System.out.println("Play Buttonunda hata meydana geldi");
               System.out.println(ex.getStackTrace());
           }
           
         }
         
        
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
      if(isOpen){
           try {
            
           OptionButtonSound =  AudioSystem.getAudioInputStream(new File("316903__jaz-the-man-2__la-stretched.wav").getAbsoluteFile());
            clip1 = AudioSystem.getClip();
          
            clip1.open(OptionButtonSound);
            clip1.start();
            
            
           
        } catch (Exception ex) {
             System.out.println("Option Buttonunda hata meydana geldi");
        }
      }
        
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        clip3.close();
        Game game = new Game(this);
       
        this.setContentPane(game);
        this.invalidate();
        this.validate();
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
   
        clip3.close();
        Option op = new Option(this);
    
        this.setContentPane(op);
        this.invalidate();
        this.validate();
        
        
    }//GEN-LAST:event_jButton2MouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    
 
}
